# Generated by Django 4.2.7 on 2024-02-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirement',
            name='govapp',
        ),
        migrations.RemoveField(
            model_name='retirement',
            name='profile',
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='retired_manually',
            field=models.BooleanField(default=False),
        ),
    ]
