# Generated by Django 4.2.7 on 2024-02-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_retirement_govapp_remove_retirement_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentappointment',
            old_name='retired_manually',
            new_name='cleared',
        ),
    ]
