# Generated by Django 4.2.7 on 2023-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='ippis_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, unique=True, verbose_name='IPPIS number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fnok_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snok_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
