# Generated by Django 5.0.4 on 2024-08-02 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='department',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
    ]
