# Generated by Django 5.0.4 on 2024-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_governmentappointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
