# Generated by Django 4.2.7 on 2023-12-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_governmentappointment_ippis_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, unique=True, verbose_name='file number'),
        ),
    ]
