# Generated by Django 4.2.7 on 2024-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_retired_manually_governmentappointment_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='grade_level',
            field=models.IntegerField(blank=True, choices=[(3, 3), (3, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)], max_length=300, null=True),
        ),
    ]
