# Generated by Django 5.0.4 on 2024-08-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NatureLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfAppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name_plural': 'Disciplinaries record'},
        ),
        migrations.RenameField(
            model_name='governmentappointment',
            old_name='retire',
            new_name='retired',
        ),
        migrations.RemoveField(
            model_name='governmentappointment',
            name='dmsg',
        ),
        migrations.RemoveField(
            model_name='governmentappointment',
            name='rtb',
        ),
        migrations.RemoveField(
            model_name='governmentappointment',
            name='type_of_appt',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='nature',
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='retire_by',
            field=models.CharField(blank=True, choices=[('DATE OF BIRTH', 'DATE OF BIRTH'), ('DATE OF FIRST APPOINTMENT', 'DATE OF FIRST APPOINTMENT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='exams_status',
            field=models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAILED', 'FAILED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='grade_level',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.gradelevel'),
        ),
        migrations.AddField(
            model_name='leave',
            name='nature_of_leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.natureleave'),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='cpost',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.post'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='cpost',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.post'),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='salary_scale',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.salaryscale'),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='type_of_cadre',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.typeofcadre'),
        ),
    ]
