# Generated by Django 4.2.7 on 2024-02-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_governmentappointment_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='govapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progovapp', to='staff.governmentappointment'),
        ),
    ]
