# Generated by Django 4.2.7 on 2024-02-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_promotion_govapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveappointment',
            name='govapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execgovapp', to='staff.governmentappointment'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='govapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtgovapp', to='staff.governmentappointment'),
        ),
    ]
