# Generated by Django 5.0.4 on 2024-08-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_gradelevel_natureleave_post_salaryscale_typeofappt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentappointment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govapp', to=settings.AUTH_USER_MODEL),
        ),
    ]
