# Generated by Django 4.2.7 on 2024-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_governmentappointment_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='due',
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='due',
            field=models.BooleanField(default=False),
        ),
    ]
