# Generated by Django 4.2.7 on 2024-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_promotion_due_governmentappointment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentappointment',
            name='dmsg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
