# Generated by Django 4.2.7 on 2024-02-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_executiveappointment_govapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='staff.profile'),
        ),
    ]
