# Generated by Django 4.2.7 on 2024-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_retirement_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='granted',
            new_name='granted_days',
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='department',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('ACCOUNT', 'ACCOUNT'), ('BIO-MEDICAL ENGR', 'BIO-MEDICAL ENGR'), ('CLINICAL SERVICES', 'CLINICAL SERVICES'), ('CATERING', 'CATERING'), ('DISCIPLINE', 'DISCIPLINE'), ('ENGINEERING', 'ENGINEERING'), ('INFORMATION TECH', 'INFORMATION TECH'), ('INTERNAL AUDIT', 'INTERNAL AUDIT'), ('LEGAL', 'LEGAL'), ('LIBRARY', 'LIBRARY'), ('MEDICAL RECORD', 'MEDICAL RECORD'), ('MEDICAL ILLUSTRATION', 'MEDICAL ILLUSTRATION'), ('NURSING EDUCATION', 'NURSING EDUCATION'), ('NURSING SERVICES', 'NURSING SERVICES'), ('PATHOLOGY', 'PATHOLOGY'), ('PHARMACY', 'PHARMACY'), ('PHYSIOTHERAPHY', 'PHYSIOTHERAPHY'), ('PROSTHETIC AND ORTHOTICS', 'PROSTHETIC AND ORTHOTICS'), ('PROCUMENT', 'PROCUMENT'), ('PUBLIC HEALTH', 'PUBLIC HEALTH'), ('OCCUPATIONAL THERAPHY', 'OCCUPATIONAL THERAPHY'), ('RADIOLOGY', 'RADIOLOGY'), ('SERVICOM', 'SERVICOM'), ('SOCIAL WELFARE', 'SOCIAL WELFARE'), ('STORE', 'STORE'), ('TELEPHONE', 'TELEPHONE'), ('TRANSPORT', 'TRANSPORT')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='governmentappointment',
            name='sfapt',
            field=models.FloatField(blank=True, max_length=300, null=True, verbose_name='salary per annum at date of first appointment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fnok_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='first next of kin photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snok_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='second next of kin photo'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retire',
            field=models.BooleanField(default=False),
        ),
    ]
