# Generated by Django 4.2.7 on 2024-03-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_governmentappointment_dmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='nature',
            field=models.CharField(blank=True, choices=[('CASUAL', 'CASUAL'), ('ANNUAL', 'ANNUAL')], max_length=7, null=True, verbose_name='nature of leave'),
        ),
    ]
