# Generated by Django 4.2.7 on 2024-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_rename_comments_leave_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirement',
            name='retire',
        ),
        migrations.RemoveField(
            model_name='retirement',
            name='rtb',
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='retire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='rtb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='retired by'),
        ),
    ]
