# Generated by Django 4.2.7 on 2024-02-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_retirement_retire_remove_retirement_rtb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentappointment',
            name='clear_rt',
            field=models.BooleanField(default=False),
        ),
    ]
