# Generated by Django 5.0.4 on 2024-08-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_rename_sen_dist_profile_senate_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='department',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
    ]
