# Generated by Django 4.2.7 on 2024-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_governmentappointment_clear_rt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentappointment',
            name='clear_rt',
        ),
        migrations.AddField(
            model_name='retirement',
            name='retire',
            field=models.BooleanField(default=False),
        ),
    ]
