# Generated by Django 5.0.4 on 2024-08-05 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_promotion_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executiveappointment',
            name='designation',
        ),
        migrations.AddField(
            model_name='executiveappointment',
            name='cpost',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.post'),
        ),
        migrations.AddField(
            model_name='executiveappointment',
            name='department',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
    ]
