# Generated by Django 4.2.7 on 2024-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_governmentappointment_clear_rt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='retire',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
