# Generated by Django 5.0.4 on 2024-08-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_executiveappointment_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='leave',
            name='nature_of_leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.leavetypes'),
        ),
        migrations.DeleteModel(
            name='NatureLeave',
        ),
    ]
