# Generated by Django 4.2.7 on 2024-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_retirement_retire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='retire',
            field=models.BooleanField(default=True),
        ),
    ]
