# Generated by Django 4.2.7 on 2024-02-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_retirement_retire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retirement',
            name='govapp',
        ),
        migrations.RemoveField(
            model_name='retirement',
            name='profile',
        ),
        migrations.AddField(
            model_name='governmentappointment',
            name='rt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.retirement'),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='retire',
            field=models.BooleanField(default=False),
        ),
    ]
