# Generated by Django 5.0.4 on 2024-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_leavetypes_alter_leave_nature_of_leave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetypes',
            options={'verbose_name_plural': 'type of leaves'},
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
