# Generated by Django 5.0.4 on 2024-08-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_leavetypes_options_leave_leave_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_count',
        ),
    ]
