# Generated by Django 4.2.7 on 2024-02-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_retirement_govapp_remove_retirement_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentappointment',
            name='rt',
        ),
        migrations.AddField(
            model_name='retirement',
            name='govapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtgovapp', to='staff.governmentappointment'),
        ),
        migrations.AddField(
            model_name='retirement',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='staff.profile'),
        ),
    ]
